name: Staging Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Staging

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build your app
      run: |
        # Your build steps, e.g.
        npm install
        npm run build

    - name: Upload build to Toolforge home dir
      uses: appleboy/scp-action@v0.1.4
      with:
        host: login.toolforge.org
        username: faridhmaulanawsc
        key: ${{ secrets.TOOLFORGE_KEY }}
        port: 22
        source: "dist/*"
        target: "~/tmp_upload/"
      
    - name: SSH into Toolforge, become tool, and deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: login.toolforge.org
        username: faridhmaulanawsc
        key: ${{ secrets.TOOLFORGE_KEY }}
        port: 22
        script: |
          become lexica-staging bash -c '
            cp -r /home/faridhmaulanawsc/tmp_upload/* /www/js/lexica-frontend/ &&
            webservice stop &&
            webservice start
          '
